# Generated by Django 3.1.7 on 2021-05-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='similar',
            field=models.CharField(default='', max_length=100),
        ),
    ]
